import crypto from "node:crypto";
import path from "node:path";
import { DATA_DIR, readJsonDir, readJsonFile, writeJsonFile } from "../data-utils.mjs";

export async function loadRouterContext() {
  const entitiesIndex = await readJsonFile(path.join(DATA_DIR, "entities", "index.json"));
  const entities = entitiesIndex.entities || [];
  const entityById = new Map(entities.map((entity) => [entity.id, entity]));
  const pipelineMap = await readJsonFile(path.join(DATA_DIR, "pipelines", "pipeline_map.json"));
  const pipelineByType = new Map((pipelineMap.routes || []).map((route) => [route.type, route.pipeline]));
  const routerRules = await readJsonFile(path.join(DATA_DIR, "router", "rules.json"));
  return { entities, entityById, pipelineByType, routerRules };
}

export async function readExistingRoutes() {
  const rows = await readJsonDir("route_decisions");
  return new Map(rows.map((row) => [row.data.rawArtifactId, row.data]));
}

export function routeArtifact(artifact, context, { createdAt = nowShanghai() } = {}) {
  const text = [
    artifact.title,
    artifact.publisher,
    artifact.url,
    artifact.artifactType,
    artifact.notes,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
  const entityRows = (artifact.entityIds || []).map((entityId) => context.entityById.get(entityId)).filter(Boolean);
  const primaryEntity = entityRows[0] || { id: "unknown", name: "unknown", kind: "unknown" };
  const signals = [];

  function add(field, value, reason) {
    signals.push({ field, value: String(value), reason });
  }

  const match = matchRouteRule(artifact, text, entityRows, context.routerRules);
  let type = match.type;
  let confidence = match.confidence;
  let reason = match.reason;
  let status = match.status;
  let nextAction = match.nextAction;
  add(match.signal.field, signalValue(match.signal.field, artifact, primaryEntity), match.signal.reason);

  const override = context.routerRules.eventOverride || {};
  if (hasAny(text, override.keywords || [])) {
    const preserveTypes = new Set(override.preserveTypes || []);
    if (!preserveTypes.has(type)) {
      type = override.type;
      confidence = confidence === "low" ? override.minimumConfidence || "medium" : confidence;
      reason = override.reason;
      status = override.status || status;
      nextAction = override.nextAction || nextAction;
    }
    add(override.signal?.field || "title", signalValue(override.signal?.field, artifact, primaryEntity), override.signal?.reason || "event signal");
  }

  const pipeline = context.pipelineByType.get(type);
  const routeStatus = status || (pipeline ? "routed" : "needs_review");
  const date = dateFrom(artifact.publishedAt || artifact.capturedAt || artifact.firstSeenAt);
  const id = `route_${date.replaceAll("-", "_")}_${hash(`${artifact.id}|${type}|${pipeline}`, 12)}`;

  return {
    id,
    rawArtifactId: artifact.id,
    type,
    entity: primaryEntity.name,
    entityId: primaryEntity.id,
    entityIds: artifact.entityIds || [],
    pipeline,
    confidence,
    reason,
    matchedSignals: signals,
    sourceKind: sourceKindFor(artifact, text, context.routerRules),
    status: routeStatus,
    createdAt,
    nextAction: nextAction || (pipeline ? `run ${pipeline}` : "manual route review"),
    notes: "Generated by route_artifact v1 rules.",
  };
}

export async function writeRouteDecision(decision) {
  await writeJsonFile(path.join(DATA_DIR, "route_decisions", `${decision.id}.json`), decision);
}

export function nowShanghai() {
  const parts = new Intl.DateTimeFormat("sv-SE", {
    timeZone: "Asia/Shanghai",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  }).format(new Date());
  return `${parts.replace(" ", "T")}+08:00`;
}

export function dateFrom(value) {
  return String(value || nowShanghai()).slice(0, 10);
}

export function hash(value, length) {
  return crypto.createHash("sha256").update(value).digest("hex").slice(0, length);
}

function matchRouteRule(artifact, text, entityRows, routerRules) {
  for (const rule of routerRules.routes || []) {
    if (!matchesRule(rule, artifact, text, entityRows)) continue;
    const artifactTypeMatched = (rule.artifactTypes || []).includes(artifact.artifactType);
    const entityKindMatched = entityRows.some((entity) => (rule.entityKinds || []).includes(entity.kind));
    return {
      type: rule.type,
      confidence:
        (artifactTypeMatched && rule.artifactTypeConfidence) ||
        (entityKindMatched && rule.entityKindConfidence) ||
        rule.confidence,
      reason: rule.reason,
      status: rule.status,
      nextAction: rule.nextAction,
      signal: rule.signal || { field: "rule", reason: `${rule.type} rule matched` },
    };
  }

  const fallback = routerRules.defaultRoute || {};
  return {
    type: fallback.type || "event",
    confidence: fallback.confidence || "low",
    reason: fallback.reason || "Default route.",
    status: fallback.status,
    nextAction: fallback.nextAction,
    signal: fallback.signal || { field: "fallback", reason: "no stronger route matched" },
  };
}

function sourceKindFor(artifact, text, routerRules) {
  for (const rule of routerRules.sourceKinds || []) {
    if (matchesRule(rule, artifact, text, [])) return rule.kind;
  }
  return routerRules.defaultSourceKind || "unknown";
}

function matchesRule(rule, artifact, text, entityRows) {
  const publisherText = String(artifact.publisher || "").toLowerCase();
  if ((rule.artifactTypes || []).includes(artifact.artifactType)) return true;
  if (hasAny(text, rule.textKeywords || [])) return true;
  if (hasAny(publisherText, rule.publisherKeywords || [])) return true;
  if ((rule.entityKinds || []).some((kind) => entityRows.some((entity) => entity.kind === kind))) return true;
  if ((rule.urlPrefixes || []).some((prefix) => String(artifact.url || "").startsWith(prefix))) return true;
  return false;
}

function signalValue(field, artifact, primaryEntity) {
  if (field === "artifact") return artifact.artifactType;
  if (field === "publisher/title") return artifact.publisher;
  if (field === "artifact/title") return `${artifact.artifactType} ${artifact.title}`;
  if (field === "entity/title") return primaryEntity.name;
  if (field === "title") return artifact.title;
  if (field === "fallback") return artifact.artifactType;
  return field || "matched";
}

function hasAny(value, needles) {
  return needles.some((needle) => String(value || "").includes(needle));
}
